
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/lucywan.github.io' #change it according to your repository name



# Profile information
yourname: Lucy Wan  ## put your name
title: 'Software Engineer'  ## your title
location: Samsara


## Social Profiles
##facebook: http://www.facebook.com  ## your facebook account url
##twitter: http://www.twitter.com  ## your twitter account url
linkedin: linkedin.com/in/lucy-wan-6844a1163  ## your linkedin account url
##dribbble: http://www.dribble.com  ## you dribbble account url
##foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.

google_analytics: UA-128069399-1
